#!/bin/tcsh -f
echo "----------------------------------------- "
echo "		 TCL WORKSHOP                   "
echo "DAY 1 : checking the file .csv exist or not"
echo "------------------------------------------"
#set working_dir ' pwd'
#echo "working directory  $working_dir "
if($#argv != 1) then
        #if (#$argv != 1) then
        echo "INFO: Please provide the .csv file only"
        exit 1
endif
if (! -f $argv[1] || $argv[1] == "-help") then
        if($argv[1] != "-help") then
                echo "Error: couldnt find .csv file $argv[1]. Exiting...."
                exit 1
     	else
        	echo "USAGE: ./vsdsynth <csv file> , where the <csv file> consists of 2 columns --> 1st column is being case sensitive."
        	echo "Note if the file is not in the same directory, ensure to include the path along with the <csv file>"
	        echo "<Design Name> is the name of the top module"
	        echo "<Output Directory> is the name of the output directory where you want to dump synthesis script, synthesized netlist and timing report"
	        echo "<Netlist Directory> is the name of the directory where all RTL netlist are present"
	        echo "<Early Library Path> is the file path of the early cell library to be used for STA"
        	echo "<Late Library Path> is the file path of the late cell library to be used for STA"
	        echo "<Constraints file> is the csv file path of constraints to be used for STA"
     		exit 1
        endif
else
	echo "INFO: $argv[1] is found in the directory "
	tclsh vsdsynth.tcl $argv[1]
endif
